# Generated by Django 4.1.5 on 2023-02-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldier', '0002_alter_company_name_alter_creed_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('adr_id', models.AutoField(primary_key=True, serialize=False)),
                ('adr_n_id', models.IntegerField()),
                ('adresa', models.CharField(max_length=360)),
            ],
            options={
                'db_table': 'adresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kontrakt',
            fields=[
                ('kontrakt_com_id', models.AutoField(primary_key=True, serialize=False)),
                ('kontrakt_date', models.DateField(blank=True, null=True)),
                ('kontrakt_srok', models.IntegerField()),
                ('kontrakt_zak', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kontrakt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nakaz',
            fields=[
                ('nak_id', models.AutoField(primary_key=True, serialize=False)),
                ('nak_n_id', models.IntegerField()),
                ('nak_status_id', models.IntegerField()),
                ('zvidky', models.IntegerField()),
                ('kudy', models.IntegerField()),
                ('nak_data', models.DateField(blank=True, null=True)),
                ('nak_nomer', models.IntegerField()),
                ('povern', models.DateField(blank=True, null=True)),
                ('tmp', models.IntegerField()),
            ],
            options={
                'db_table': 'nakaz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NakazNomer',
            fields=[
                ('n_nak_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_nak_data', models.DateField(blank=True, null=True)),
                ('n_nak_nomer', models.IntegerField()),
            ],
            options={
                'db_table': 'nakaz_nomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NakazPlace',
            fields=[
                ('nak_place_id', models.AutoField(primary_key=True, serialize=False)),
                ('nak_place_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'nakaz_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('pseudo', models.CharField(max_length=128)),
                ('data_zv', models.CharField(max_length=100)),
                ('pos_id_old', models.IntegerField(blank=True, null=True)),
                ('p_id', models.IntegerField()),
                ('kontr', models.IntegerField(blank=True, null=True)),
                ('data_narod', models.DateField(blank=True, null=True)),
                ('adresa_nar', models.CharField(max_length=200)),
                ('data_mob', models.DateField(blank=True, null=True)),
                ('vijskomat', models.CharField(max_length=100)),
                ('data_zarah', models.DateField(blank=True, null=True)),
                ('nomer_nakazu_ok', models.CharField(max_length=10)),
                ('data_nakazu_ok', models.DateField(blank=True, null=True)),
                ('chiy_nakaz', models.CharField(max_length=50)),
                ('kontrakt', models.DateField(blank=True, null=True)),
                ('kontrakt_strok', models.CharField(max_length=50)),
                ('kontrakt_zak', models.DateField(blank=True, null=True)),
                ('nomer_nakazu', models.IntegerField()),
                ('data_zviln', models.DateField(blank=True, null=True)),
                ('nomer_nakazu_zviln', models.IntegerField()),
                ('nomer_pasp', models.CharField(max_length=100)),
                ('code_nomer', models.CharField(max_length=10)),
                ('voen_nomer', models.CharField(max_length=25)),
                ('grupa_krovi', models.CharField(max_length=15)),
                ('specialnist', models.CharField(max_length=500)),
                ('zvp', models.CharField(max_length=100)),
                ('fahova', models.CharField(max_length=100)),
                ('liderstvo', models.CharField(max_length=100)),
                ('perem', models.CharField(max_length=50)),
                ('persh_kontr', models.CharField(max_length=50)),
                ('ozdor', models.CharField(max_length=50)),
                ('mdspp', models.CharField(max_length=50)),
                ('status2', models.IntegerField()),
                ('notes', models.TextField()),
                ('notes1', models.TextField()),
            ],
            options={
                'db_table': 'name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsvitaName',
            fields=[
                ('osv_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('osv_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'osvita_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peremish',
            fields=[
                ('perem_id', models.AutoField(primary_key=True, serialize=False)),
                ('perem_n_id', models.IntegerField()),
                ('perem_status_id', models.IntegerField()),
                ('zvidky', models.IntegerField()),
                ('kudy', models.IntegerField()),
                ('perem_data', models.DateField(blank=True, null=True)),
                ('nakaz_id', models.IntegerField()),
                ('povern', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peremish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('ph_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_id', models.IntegerField()),
                ('ph_nomer', models.TextField()),
            ],
            options={
                'db_table': 'phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PidrozdilId',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_parent_id', models.IntegerField()),
                ('isparent', models.IntegerField()),
            ],
            options={
                'db_table': 'pidrozdil_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PidrozdilName',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('por_nomer', models.IntegerField()),
                ('p_name', models.TextField()),
                ('p_short_name', models.CharField(max_length=32)),
                ('p_full_name', models.CharField(max_length=200)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'pidrozdil_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosadaName',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_name', models.TextField()),
            ],
            options={
                'db_table': 'posada_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priznach',
            fields=[
                ('prizn_id', models.AutoField(primary_key=True, serialize=False)),
                ('prizn_n_id', models.IntegerField()),
                ('prizn_data', models.DateField(blank=True, null=True)),
                ('prizn_pos_id', models.IntegerField()),
            ],
            options={
                'db_table': 'priznach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriznachOld',
            fields=[
                ('prizn_id', models.AutoField(primary_key=True, serialize=False)),
                ('prizn_n_id', models.IntegerField()),
                ('prizn_data', models.DateField(blank=True, null=True)),
                ('prizn_pos_id', models.IntegerField()),
            ],
            options={
                'db_table': 'priznach_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriznachOld2',
            fields=[
                ('prizn_id', models.AutoField(primary_key=True, serialize=False)),
                ('prizn_n_id', models.IntegerField()),
                ('prizn_data', models.DateField(blank=True, null=True)),
                ('prizn_pos_id', models.IntegerField()),
            ],
            options={
                'db_table': 'priznach_old_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ridny',
            fields=[
                ('rid_id', models.AutoField(primary_key=True, serialize=False)),
                ('rid_n_id', models.IntegerField()),
                ('rid_name_id', models.IntegerField()),
                ('rid_name', models.CharField(max_length=200)),
                ('rid_data_nar', models.DateField(blank=True, null=True)),
                ('rid_phone', models.IntegerField()),
                ('rid_notes', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ridny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RidnyName',
            fields=[
                ('rid_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('rid_name_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ridny_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shtatka',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('dopusk', models.CharField(max_length=1)),
                ('vos', models.CharField(max_length=12)),
                ('oklad', models.CharField(max_length=12)),
                ('vidsotok', models.IntegerField()),
                ('nomer_kniga', models.IntegerField()),
            ],
            options={
                'db_table': 'shtatka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShtatkaOld',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('sh_id', models.IntegerField()),
                ('zv_sh_id', models.IntegerField()),
                ('vos', models.CharField(max_length=12)),
                ('oklad', models.CharField(max_length=12)),
                ('nomer_kniga', models.IntegerField()),
            ],
            options={
                'db_table': 'shtatka_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShtatkaOld2',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('sh_id', models.IntegerField()),
                ('zv_sh_id', models.IntegerField()),
                ('vos', models.CharField(max_length=12)),
                ('oklad', models.CharField(max_length=12)),
                ('nomer_kniga', models.IntegerField()),
            ],
            options={
                'db_table': 'shtatka_old_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimStanName',
            fields=[
                ('s_stan_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_stan_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sim_stan_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatsName',
            fields=[
                ('s_stats_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_stats_name', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'stats_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusName',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'status_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(blank=True, db_column='COL 1', max_length=10, null=True)),
                ('col_2', models.IntegerField(blank=True, db_column='COL 2', null=True)),
            ],
            options={
                'db_table': 'table 32',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table35',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(blank=True, db_column='COL 1', max_length=10, null=True)),
                ('col_2', models.IntegerField(blank=True, db_column='COL 2', null=True)),
            ],
            options={
                'db_table': 'table 35',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField(db_column='1')),
                ('number_2', models.TextField(db_column='2')),
            ],
            options={
                'db_table': 'temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField(db_column='1')),
                ('number_2', models.TextField(db_column='2')),
            ],
            options={
                'db_table': 'tmp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vysluga',
            fields=[
                ('vys_id', models.AutoField(primary_key=True, serialize=False)),
                ('vys_n_id', models.IntegerField()),
                ('vys_data_mob', models.DateField(blank=True, null=True)),
                ('vys_data_zvil', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vysluga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VyslugaNormy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rokiv', models.IntegerField()),
                ('nadbavka', models.IntegerField()),
            ],
            options={
                'db_table': 'vysluga_normy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VyslugaZv',
            fields=[
                ('vys_zv_id', models.AutoField(primary_key=True, serialize=False)),
                ('vys_zv_n_id', models.IntegerField()),
                ('data_zv', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vysluga_zv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zbroya',
            fields=[
                ('zbr_id', models.AutoField(primary_key=True, serialize=False)),
                ('zbr_type', models.IntegerField()),
                ('nomer', models.CharField(max_length=128)),
                ('n_id', models.IntegerField()),
                ('magazin', models.IntegerField()),
                ('zbr_status', models.IntegerField()),
                ('zbr_note', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zbroya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZbroyaAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zbr_type', models.IntegerField()),
                ('nomer', models.CharField(max_length=128)),
                ('rota', models.IntegerField()),
            ],
            options={
                'db_table': 'zbroya_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZbroyaName',
            fields=[
                ('zbr_id', models.AutoField(primary_key=True, serialize=False)),
                ('zbr_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'zbroya_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZbroyaSklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zbr_type', models.IntegerField()),
                ('nomer', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zbroya_sklad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZbrStatusName',
            fields=[
                ('zbr_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('zbr_status_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zbr_status_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZvannyaId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zv_id', models.IntegerField(unique=True)),
                ('zv_gr_id', models.IntegerField()),
                ('zv_okl', models.IntegerField()),
            ],
            options={
                'db_table': 'zvannya_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZvannyaName',
            fields=[
                ('zv_id', models.AutoField(primary_key=True, serialize=False)),
                ('zv_name', models.TextField()),
                ('zv_short_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zvannya_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZvGrupaName',
            fields=[
                ('zv_gr_id', models.AutoField(primary_key=True, serialize=False)),
                ('zv_gr_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zv_grupa_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZvilnComent',
            fields=[
                ('zv_com_id', models.AutoField(primary_key=True, serialize=False)),
                ('zv_com_n_id', models.IntegerField()),
                ('zv_coment', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'zviln_coment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SHPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
                ('short_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short name')),
            ],
            options={
                'verbose_name': 'SHPK',
                'verbose_name_plural': 'SHPK',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicum', models.PositiveBigIntegerField(blank=True, verbose_name='Unic number')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
                ('vos', models.CharField(max_length=512, verbose_name='VOS')),
                ('poz', models.CharField(blank=True, max_length=512, verbose_name='pozyvnyy')),
                ('salary', models.PositiveBigIntegerField(blank=True, verbose_name='salary')),
                ('tariff_category', models.PositiveBigIntegerField(blank=True, verbose_name='tariff category')),
                ('vacant', models.BooleanField(blank=True, default=True, null=True, verbose_name='Vacant')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.company', verbose_name='Company')),
                ('ocoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='ocoba')),
                ('shpk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.shpk', verbose_name='shpk')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
