# Generated by Django 4.1.5 on 2023-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_salary_alter_staff_tariff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unicum',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Unic number'),
        ),
    ]
