# Generated by Django 4.1.5 on 2023-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_unicum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shpk',
            options={'verbose_name': 'ШПК', 'verbose_name_plural': 'ШПК'},
        ),
        migrations.AlterField(
            model_name='shpk',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='shpk',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Скорочене імʼя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='unicum',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Унікальний номер'),
        ),
    ]
