# Generated by Django 4.1.5 on 2023-02-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_shpk_options_alter_shpk_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Унікальний номер')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name="ім'я")),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="ім'я")),
            ],
            options={
                'verbose_name': 'Battalion',
                'verbose_name_plural': 'Battalions',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Унікальний номер')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name="ім'я")),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="ім'я")),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Унікальний номер')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name="ім'я")),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="ім'я")),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взвода',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Унікальний номер')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name="ім'я")),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="ім'я")),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squads',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='battalion',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='staff.battalion', verbose_name='Battalion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='platoon',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='staff.platoon', verbose_name='Взвод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='squad',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, to='staff.squad', verbose_name='Squad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.company', verbose_name='Company'),
        ),
    ]
