# Generated by Django 4.1.5 on 2023-02-10 09:56

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django_jsonform.models.fields.JSONField()),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
