# Generated by Django 4.1.5 on 2023-02-10 12:03

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django_jsonform.models.fields.JSONField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ammunition',
            options={'verbose_name': 'Ammunition', 'verbose_name_plural': 'Ammunition'},
        ),
    ]
