# Generated by Django 4.1.5 on 2023-02-13 14:29

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0004_alter_invoice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
