# Generated by Django 4.1.5 on 2023-02-13 14:39

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0005_alter_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=django_jsonform.models.fields.JSONField(default=6),
            preserve_default=False,
        ),
    ]
