# Generated by Django 4.1.5 on 2023-02-13 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0006_alter_invoice_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Full name')),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=7, max_length=50, verbose_name='Число'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.service', verbose_name='Service'),
            preserve_default=False,
        ),
    ]
