# Generated by Django 4.1.5 on 2023-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0007_service_alter_invoice_options_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Full name')),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
            ],
            options={
                'verbose_name': 'Consignee',
                'verbose_name_plural': 'Consignees',
            },
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Full name')),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
            ],
            options={
                'verbose_name': 'Consignor',
                'verbose_name_plural': 'Consignors',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Full name')),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
            ],
            options={
                'verbose_name': 'Responsible Recipient',
                'verbose_name_plural': 'Responsible Recipients',
            },
        ),
    ]
