# Generated by Django 4.1.5 on 2023-02-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0008_consignee_consignor_responsiblerecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.service', verbose_name='Service'),
        ),
    ]
