# Generated by Django 4.1.5 on 2023-02-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0009_alter_serviseid_award_alter_serviseid_battle_wound'),
        ('gunwarehouse', '0009_alter_invoice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.consignee', verbose_name='Consignee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.consignor', verbose_name='Consignor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='responsible_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='ResponsibleRecipient'),
        ),
    ]
