# Generated by Django 4.1.5 on 2023-02-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0010_invoice_consignee_invoice_consignor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Full name')),
                ('name', models.CharField(max_length=512, verbose_name='Імʼя')),
            ],
            options={
                'verbose_name': 'Gun Warehouse',
                'verbose_name_plural': 'Gun Warehouses',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='gun_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.gunwarehouse', verbose_name='Gun Warehouse'),
        ),
    ]
