# Generated by Django 4.1.5 on 2023-02-28 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0010_alter_award_options_alter_battlewound_options_and_more'),
        ('gunwarehouse', '0012_invoice_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammunition',
            options={'verbose_name': 'Боєприпас', 'verbose_name_plural': 'Боєприпас'},
        ),
        migrations.AlterModelOptions(
            name='consignee',
            options={'verbose_name': 'Вантажоодержувач', 'verbose_name_plural': 'Вантажоодержувачі'},
        ),
        migrations.AlterModelOptions(
            name='consignor',
            options={'verbose_name': 'Вантажовідправник', 'verbose_name_plural': 'Вантажовідправники'},
        ),
        migrations.AlterModelOptions(
            name='gunwarehouse',
            options={'verbose_name': 'Зброярки', 'verbose_name_plural': 'Зброярки'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Накладна', 'verbose_name_plural': 'Накладні'},
        ),
        migrations.AlterModelOptions(
            name='responsiblerecipient',
            options={'verbose_name': 'Відповідальний отримувач', 'verbose_name_plural': 'Відповідальні отримувачі'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Служба', 'verbose_name_plural': 'Служби'},
        ),
        migrations.AlterField(
            model_name='ammunition',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='consignee',
            name='full_name',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='full_name',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='gunwarehouse',
            name='full_name',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.consignee', verbose_name='Вантажоодержувач'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.consignor', verbose_name='Вантажовідправник'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gun_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.gunwarehouse', verbose_name='Зброярки'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(choices=[('1', 'Приход'), ('2', 'З складу')], default='2', max_length=50, verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='responsible_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='Відповідальний одержувач'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.service', verbose_name='Служба'),
        ),
        migrations.AlterField(
            model_name='responsiblerecipient',
            name='full_name',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_name',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
    ]
