# Generated by Django 4.1.5 on 2023-03-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0013_alter_ammunition_options_alter_consignee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='good_class',
            field=models.CharField(choices=[('1', 'Приход'), ('2', 'З складу')], default='2', max_length=50, verbose_name='Good class'),
        ),
    ]
