# Generated by Django 4.1.5 on 2023-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0015_weapon_alter_invoice_good_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(default=15, max_length=512, verbose_name='Імʼя'),
            preserve_default=False,
        ),
    ]
