# Generated by Django 4.1.5 on 2023-03-03 10:29

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0016_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='additional',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
