# Generated by Django 4.1.5 on 2023-03-03 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0010_alter_award_options_alter_battlewound_options_and_more'),
        ('gunwarehouse', '0017_alter_weapon_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Weapon', 'verbose_name_plural': 'Weapons'},
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type_weapon',
            field=models.CharField(choices=[('1', 'Pistol'), ('2', 'Rifle'), ('3', 'Machinegun'), ('4', 'Grenade launcher'), ('5', 'Sniper rifle'), ('6', 'Large-caliber weapon')], default=1, max_length=50, verbose_name='Type Weapon'),
        ),
        migrations.CreateModel(
            name='InvoiceWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата створення')),
                ('weapons', django_jsonform.models.fields.JSONField()),
                ('gun_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gunwarehouse.gunwarehouse', verbose_name='Зброярки')),
                ('responsible_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='Відповідальний одержувач')),
            ],
            options={
                'verbose_name': 'Invoice Weapon',
                'verbose_name_plural': 'Invoice Weapons',
            },
        ),
    ]
