# Generated by Django 4.1.5 on 2023-03-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunwarehouse', '0018_alter_weapon_options_alter_weapon_type_weapon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceweapon',
            options={'verbose_name': 'Накладна на зброю', 'verbose_name_plural': 'Накладні на зброю'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'зброя', 'verbose_name_plural': 'Зброя'},
        ),
        migrations.AddField(
            model_name='invoiceweapon',
            name='purpose',
            field=models.CharField(choices=[('1', 'Приход'), ('2', 'З складу')], default='2', max_length=50, verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='good_class',
            field=models.CharField(choices=[('1', 'Боєприпас'), ('2', 'Зброя'), ('3', 'Прилад')], default='2', max_length=50, verbose_name='Тип речі'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='calibre',
            field=models.CharField(max_length=50, verbose_name='Калібр'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='issued',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не видана'), (2, 'Видана'), (3, 'Втрачена')], default=1, verbose_name='Видана'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='serial_number',
            field=models.CharField(max_length=256, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type_weapon',
            field=models.CharField(choices=[('1', 'Пістолет(Пістолет-кулемет)'), ('2', 'Гвинтівка'), ('3', 'Кулемет'), ('4', 'Гранатомет'), ('5', 'Снайперська гвинтівка'), ('6', 'Крупно-каліберна зброя')], default=1, max_length=50, verbose_name='Тип зброї'),
        ),
    ]
