# Generated by Django 4.1.5 on 2023-02-01 09:04

from django.db import migrations, models
import django.db.models.deletion
import soldier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unik', models.PositiveBigIntegerField(blank=True, verbose_name='Unic number')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('short_name', models.CharField(max_length=512, verbose_name='Short name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Creed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Creed',
                'verbose_name_plural': 'Creed',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short name')),
            ],
            options={
                'verbose_name': 'Military Rank',
                'verbose_name_plural': 'Military Ranks',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('shpk', models.CharField(max_length=512, verbose_name='SHPK')),
            ],
            options={
                'verbose_name': 'Official Position',
                'verbose_name_plural': 'Official Positions',
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('priorety', models.SmallIntegerField(default=1, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Platoon',
                'verbose_name_plural': 'Platoons',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='ServiseID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name Person')),
                ('sename', models.CharField(max_length=512, verbose_name='Sename')),
                ('third_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='third name')),
                ('nickname', models.CharField(blank=True, max_length=512, null=True, verbose_name='nickname')),
                ('name_accs', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name Person in accs')),
                ('sename_accs', models.CharField(blank=True, max_length=512, null=True, verbose_name='Sename in accs')),
                ('third_name_accs', models.CharField(blank=True, max_length=512, null=True, verbose_name='third name  in accs')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('image3x4', models.BinaryField(blank=True, verbose_name='image3x4')),
                ('image_face3x4', models.ImageField(blank=True, upload_to=soldier.models.image_directory_path, verbose_name='image_face3x4')),
                ('military_office', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Military office')),
                ('date_of_conscription', models.DateField(blank=True, null=True, verbose_name='date of conscription')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='order date')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='order number')),
                ('militaryID_seria', models.CharField(blank=True, max_length=3, null=True, verbose_name='militaryID seria')),
                ('militaryID_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='militaryID number')),
                ('who_militaryID', models.CharField(blank=True, max_length=10, null=True, verbose_name='who_militaryID')),
                ('militaryID_date', models.DateField(blank=True, null=True, verbose_name='militaryID_date')),
                ('weapon', models.CharField(blank=True, max_length=1020, null=True, verbose_name='weapon')),
                ('military_rank_id', models.CharField(blank=True, max_length=1020, null=True, verbose_name='military_rank_id')),
                ('military_rank_date', models.DateField(blank=True, null=True, verbose_name='military_rank_date')),
                ('ID_seria', models.CharField(blank=True, max_length=3, null=True, verbose_name='ID seria')),
                ('ID_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID number')),
                ('who_ID', models.CharField(blank=True, max_length=10, null=True, verbose_name='who_ID')),
                ('ID_date', models.DateField(blank=True, null=True, verbose_name='ID_date')),
                ('ipn', models.CharField(blank=True, max_length=10, null=True, verbose_name='ipn')),
                ('orphan', models.BooleanField(default=False, help_text='orphan', verbose_name='orphan')),
                ('married', models.BooleanField(default=False, verbose_name='married')),
                ('halforphan', models.BooleanField(default=False, verbose_name='halforphan')),
                ('work', models.BooleanField(default=False, verbose_name='work')),
                ('mobilization', models.BooleanField(default=False, verbose_name='mobilization')),
                ('driveid', models.BooleanField(default=False, verbose_name='driveid')),
                ('driveid_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='driveid category')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='blood_type')),
                ('rh', models.CharField(blank=True, max_length=2, null=True, verbose_name='RH')),
                ('addres_pr', models.TextField(blank=True, null=True, verbose_name='addres_pr')),
                ('postal_code_pr', models.CharField(blank=True, max_length=25, null=True, verbose_name='postal code_pr')),
                ('addres_fact', models.TextField(blank=True, null=True, verbose_name='address fact')),
                ('postal_code_fact', models.CharField(blank=True, max_length=25, null=True, verbose_name='postal code')),
                ('phone1', models.CharField(blank=True, max_length=25, null=True, verbose_name='phone home')),
                ('phone2', models.CharField(blank=True, max_length=25, null=True, verbose_name='phone mobile')),
                ('father', models.CharField(blank=True, max_length=500, null=True, verbose_name='father')),
                ('mother', models.CharField(blank=True, max_length=500, null=True, verbose_name='mother')),
                ('partner', models.CharField(blank=True, max_length=500, null=True, verbose_name='partner')),
                ('creed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.creed', verbose_name='creed')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.education', verbose_name='Education')),
                ('military_ranks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldier.militaryrank', verbose_name='military rank')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.nationality', verbose_name='nationality')),
                ('region_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.region', verbose_name='region fact')),
                ('region_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.region', verbose_name='region')),
                ('state_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.state', verbose_name='state fact')),
                ('state_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'ServiseID',
                'verbose_name_plural': 'ServiseIDs',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KB', 'Battalion commander'), ('ZKB', 'Deputy Battalion Commander'), ('ZKBMPZ', 'Deputy Battalion Commander for Moral and Psychological Support'), ('PKBZPR', 'Assistant Battalion Commander for Legal Affairs'), ('OP', 'Officer-psychologist'), ('GSVCH', 'Chief sergeant of a military unit'), ('Tehnic', 'Technician'), ('ZKBPDP', 'Deputy Battalion Commander for Airborne Training'), ('ZKBNSH', 'Chief of Staff - First Deputy Battalion Commander'), ('SPZKISCH', 'Senior assistant chief of staff for personnel and military units')], max_length=512, verbose_name='Name Command')),
                ('temporarily', models.PositiveSmallIntegerField(default=0, verbose_name='TVO')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='Name Person')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
            },
        ),
    ]
