# Generated by Django 4.1.5 on 2023-02-02 14:32

from django.db import migrations, models
import soldier.models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0003_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=soldier.models.file_upload_to_directory),
        ),
    ]
