# Generated by Django 4.1.5 on 2023-02-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0004_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creed',
            options={'verbose_name': 'Віросповідання', 'verbose_name_plural': 'Віросповідання'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Освіта', 'verbose_name_plural': 'Освіта'},
        ),
        migrations.AlterModelOptions(
            name='militaryrank',
            options={'verbose_name': 'Військове звання', 'verbose_name_plural': 'Військові звання'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Національність', 'verbose_name_plural': 'Національності'},
        ),
        migrations.AlterModelOptions(
            name='platoon',
            options={'verbose_name': 'Взвод', 'verbose_name_plural': 'Взвода'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Райони'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Області'},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldier.serviseid', verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=512, verbose_name='Скорочене імʼя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='unik',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Унікальний номер'),
        ),
        migrations.AlterField(
            model_name='creed',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='militaryrank',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='militaryrank',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Скорочене імʼя'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='officialposition',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='officialposition',
            name='shpk',
            field=models.CharField(max_length=512, verbose_name='ШПК'),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='priorety',
            field=models.SmallIntegerField(default=1, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='birth_date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='creed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.creed', verbose_name='віросповідання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='driveid',
            field=models.BooleanField(default=False, verbose_name='водійське посвідчення'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.education', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='image3x4',
            field=models.BinaryField(blank=True, verbose_name='Фото 3Х4'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_office',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Воєнкомат'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_ranks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldier.militaryrank', verbose_name='Військове звання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldier.nationality', verbose_name='національність'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='nickname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Позивний'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='sename',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='third_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Імʼя'),
        ),
    ]
