# Generated by Django 4.1.5 on 2023-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0005_alter_creed_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleWound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Official Position',
                'verbose_name_plural': 'Official Positions',
            },
        ),
        migrations.AddField(
            model_name='serviseid',
            name='battle_wound',
            field=models.ManyToManyField(blank=True, null=True, to='soldier.battlewound', verbose_name='battle wound'),
        ),
    ]
