# Generated by Django 4.1.5 on 2023-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0006_battlewound_serviseid_battle_wound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
            },
        ),
        migrations.AlterModelOptions(
            name='battlewound',
            options={'verbose_name': 'Battle Wound', 'verbose_name_plural': 'Battle Wounds'},
        ),
        migrations.AddField(
            model_name='serviseid',
            name='reward',
            field=models.ManyToManyField(blank=True, null=True, to='soldier.reward', verbose_name='reward'),
        ),
    ]
