# Generated by Django 4.1.5 on 2023-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0007_reward_alter_battlewound_options_serviseid_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='Award',
        ),
        migrations.RenameField(
            model_name='serviseid',
            old_name='reward',
            new_name='award',
        ),
    ]
