# Generated by Django 4.1.5 on 2023-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0008_rename_reward_award_rename_reward_serviseid_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviseid',
            name='award',
            field=models.ManyToManyField(blank=True, to='soldier.award', verbose_name='reward'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='battle_wound',
            field=models.ManyToManyField(blank=True, to='soldier.battlewound', verbose_name='battle wound'),
        ),
    ]
