# Generated by Django 4.1.5 on 2023-02-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0009_alter_serviseid_award_alter_serviseid_battle_wound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Нагорода', 'verbose_name_plural': 'Нагороди'},
        ),
        migrations.AlterModelOptions(
            name='battlewound',
            options={'verbose_name': 'Бойові поранення', 'verbose_name_plural': 'Бойові поранення'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Рота', 'verbose_name_plural': 'Рота'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Взвод', 'verbose_name_plural': 'Взвода'},
        ),
        migrations.AlterField(
            model_name='command',
            name='temporarily',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ТВО'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='ID_date',
            field=models.DateField(blank=True, null=True, verbose_name='Паспорт дата видачі'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='ID_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Паспорт номер'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='ID_seria',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Паспорт серія'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='addres_fact',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса фактично'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='addres_pr',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса проживання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='award',
            field=models.ManyToManyField(blank=True, to='soldier.award', verbose_name='Нагороди'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='battle_wound',
            field=models.ManyToManyField(blank=True, to='soldier.battlewound', verbose_name='Бойові поранення'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Група крові'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='date_of_conscription',
            field=models.DateField(blank=True, null=True, verbose_name='Дата призову'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='driveid_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Водійські права категорії'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='father',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Батько'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='halforphan',
            field=models.BooleanField(default=False, verbose_name='Напівсирота'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='married',
            field=models.BooleanField(default=False, verbose_name='Одружений'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_date',
            field=models.DateField(blank=True, null=True, verbose_name='Військовий квиток дата'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Військовий квиток номер'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_seria',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Військовий квиток серія'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_rank_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присвоєння звання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_rank_id',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Звання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='mobilization',
            field=models.BooleanField(default=False, verbose_name='Мобілізація'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='mother',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Мати'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата логовору'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договору'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='orphan',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='Сирота'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='partner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Домашній телефон'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='postal_code_fact',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Індекс'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='postal_code_pr',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Індекс проживання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='region_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.region', verbose_name='Район фактично'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='region_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.region', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='rh',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Резус'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='state_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.state', verbose_name='Область фактично'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='state_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soldier.state', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='weapon',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='зброя'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='who_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Хто видав паспорт'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='who_militaryID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Хто видав військовий квиток '),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='work',
            field=models.BooleanField(default=False, verbose_name='Робота'),
        ),
    ]
