# Generated by Django 4.1.5 on 2023-03-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0010_alter_award_options_alter_battlewound_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviseid',
            options={'verbose_name': 'Військовослужбовець', 'verbose_name_plural': 'Військовослужбовці'},
        ),
    ]
